#!/bin/sh

# ddns - update <a> record

# Copyright (c) 2012 Jason Schulz <http://github.com/uxcn>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# author: jason

USAGE="
ddns <cmd> [cmd args...]        \n
                                \n
commands                        \n
                                \n
set\t- set ddns address         \n
sync\t- sync ddns address"

CMD=$1

SERVER=$2
USER=$3
PW=$4

DOMAIN=$5
IF=$6

A=$7

RUSER=$8
RHOST=$9

if [[ ${CMD} == "set" ]]; then

    if [[ $# -lt 7 ]]; then
        echo -e "ddns set <server> <user> <password> <domain> <if> <a> [<ruser> <rhost>]"
        exit 1
    fi

    if [[ ! -z $RUSER &&
            ! -z $RHOST ]]; then

        EXEC="/usr/bin/ssh -q ${RUSER}@${RHOST}"

    fi

    CUR=`${EXEC} \
        /sbin/ifconfig ${IF} |         \
        /usr/bin/head -n 2 |           \
        /usr/bin/tail -n 1 |           \
        /usr/bin/awk '{ print $2 }' |  \
        /bin/sed s/addr://`

    /usr/bin/wget -O - \
        "https://${SERVER}/update?user=${USER}&password=${PW}&domain=${DOMAIN}&ip=${CUR}&host=${A}" 2>/dev/null \
        | /bin/grep -q '<ErrCount>0</ErrCount>'

    if [[ $? -ne 0 ]]; then
    
        echo -e "warn: unable to set [${A}.${DOMAIN}] -> ($CUR)"
        exit 1
    
    fi

    ${EXEC} /usr/sbin/nvram set ${IF}_inet\=${CUR}
    ${EXEC} /usr/sbin/nvram commit

    exit 0

fi

if [[ ${CMD} == "sync" ]]; then

    if [[ $# -lt 7 ]]; then
        echo -e "ddns sync <server> <user> <password> <domain> <if> <a> [<ruser> <rhost>]"
        
        exit 1
    fi

    if [[ ! -z $RUSER &&
            ! -z $RHOST ]]; then

        EXEC="/usr/bin/ssh -q ${RUSER}@${RHOST}"

    fi

    PRE=`${EXEC} /usr/sbin/nvram get ${IF}_inet`
    CUR=`${EXEC} \
        /sbin/ifconfig ${IF} |         \
        /usr/bin/head -n 2 |           \
        /usr/bin/tail -n 1 |           \
        /usr/bin/awk '{ print $2 }' |  \
        /bin/sed s/addr://`


    if [[ ${CUR} == ${PRE} ]]; then
        exit 0
    fi

    echo -e "info: address changed ${PRE} -> ${CUR} (${IF})"
    
    /usr/bin/wget -O - \
        "https://${SERVER}/update?user=${USER}&password=${PW}&domain=${DOMAIN}&ip=${CUR}&host=${A}" 2>/dev/null \
        | /bin/grep -q '<ErrCount>0</ErrCount>'
    
    if [[ $? -ne 0 ]]; then

        echo -e "warn: unable to sync [${A}.${DOMAIN}] -> ($CUR)"
        exit 1
    
    fi

    ${EXEC} /usr/sbin/nvram set ${IF}_inet\=${CUR}
    ${EXEC} /usr/sbin/nvram commit

    exit 0

fi

echo -e ${USAGE}
exit 1

