#!/bin/sh

# knock - knock decorator

# Copyright (c) 2012 Jason Schulz <http://github.com/uxcn>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# author: jason

USAGE="knock [arg...] <host>"

if (( $# < 1 )); then
    echo -e ${USAGE}
    exit 1
fi

ARGS=( "$@" )
HOST=${ARGS[-1]}

unset ARGS[-1]

if [[ ! -e ~/.knock/${HOST} ]]; then

    echo -e "$0: unknown key (${HOST})" >&2
    exit 1

fi

read KEY < ~/.knock/${HOST}
/usr/bin/knock "${ARGS[@]}" ${HOST} ${KEY}

