#!/bin/sh

# newsbeuter - newsbeuter decorator

# Copyright (c) 2014 Jason Schulz <http://github.com/uxcn>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# author: jason

USAGE="newsbeuter [arg...]"

CD=~/feeds/newsbeuter

if [[ ! -e ${CD}/cache.db ]]; then

  exec /usr/bin/newsbeuter "$@"

fi

PRE=`/bin/ls -l --time-style=long-iso ${CD}/cache.db | /bin/tail -n 1 | /bin/awk '{print $6}'`
NXT=`/bin/date +%Y-%m-%d`

PRE=${PRE%-*}
NXT=${NXT%-*}

if [[ ${PRE} != ${NXT} ]]; then

  /bin/mv ${CD}/cache.db ${CD}/cache.${PRE}.db

  if (( $? != 0 ));then

    echo -e "error: unable to archive cache"
    exit 1

  fi

fi

exec /usr/bin/newsbeuter "$@"
