#!/bin/sh

# smux - ssh multiple hosts using tmux

# Copyright (c) 2014 Jason Schulz <http://github.com/uxcn>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


# author: jason

USAGE="smux [-s] <domain> <host> [host...]"


if [[ $1 == '-s' ]]; then

  SYNC=1
  shift 1

fi

if (( $# < 2 )); then

  echo -e ${USAGE}
  exit 1

fi

DOMAIN=$1
shift 1

HOST=`hostname`
HOSTS=( $@ )

SESSION=${DOMAIN//./-}
SESSIONS=`tmux list-sessions | grep -c ${SESSION}-\\\?[0-9]*`

if (( ${SESSIONS} > 0 )); then
  SESSION+="-${SESSIONS}"
fi

tmux new -s ${SESSION} -d

if [[ ${HOSTS[0]} != $HOST  ]]; then

  tmux send-keys -t ${SESSION} "ssh ${HOSTS[0]}.${DOMAIN}" C-m 
  tmux send-keys -t ${SESSION} "clear" C-m

fi

for ((i=1; i<${#HOSTS[@]}; i++)); do

  tmux split-window -t ${SESSION}

  if [[ ${HOSTS[$i]} != ${HOST} ]]; then

    tmux send-keys -t ${SESSION} "ssh ${HOSTS[$i]}.${DOMAIN}" C-m 
    tmux send-keys -t ${SESSION} "clear" C-m

  fi

done

tmux select-layout -t ${SESSION} tiled

if [[ ! -z ${SYNC} ]]; then

  tmux set-window-option -t ${SESSION} synchronize-panes on 

fi

tmux select-pane -t ${SESSION}:0.0
exec tmux attach -t ${SESSION}

